lib/scorables/time_read.rb
spec/lib/scorables/shared_scorables_spec.rb

calculate time_read by hours not seconds

fix time_read

---

assets/javascripts/discourse/components/gamification-leaderboard.js
assets/javascripts/discourse/helpers/kformatter.js
assets/javascripts/discourse/templates/components/gamification-leaderboard-row.hbs
assets/javascripts/discourse/templates/components/gamification-leaderboard.hbs
assets/stylesheets/common/leaderboard.scss
assets/stylesheets/desktop/leaderboard.scss

<s>I didn't know where to find the correct i18n helper that was mentioned in topic, so did something else that I think/hope works. It's probably not very elegant so feel free to replace it.</s> – Replaced
Also left a comment in because I strongly assume an actual dev will want to change what I did there.

FEATURE: row highlighting for currentuser + number formatting

---

assets/javascripts/discourse/templates/components/gamification-leaderboard.hbs
assets/javascripts/discourse/templates/modal/leaderboard-info.hbs
assets/stylesheets/common/leaderboard.scss
assets/stylesheets/desktop/leaderboard.scss
assets/stylesheets/mobile/leaderboard.scss

UX: downscale podium + locale fixes

---

assets/javascripts/discourse/helpers/format.js
assets/javascripts/discourse/helpers/fullnumber.js
assets/javascripts/discourse/templates/components/gamification-leaderboard-row.hbs
assets/javascripts/discourse/templates/components/gamification-leaderboard.hbs

Changed the shorthand version to only be used on mobile (desktop has enough space for the full number)

UX: number shorthand on mobile-only

---

app/controllers/gamification_leaderboard_controller.rb
app/models/gamification_leaderboard.rb
app/serializers/leaderboard_view_serializer.rb
assets/javascripts/discourse/components/gamification-leaderboard.js
assets/javascripts/discourse/templates/components/gamification-leaderboard.hbs
assets/stylesheets/common/leaderboard.scss
assets/stylesheets/mobile/leaderboard.scss

[recording_20220713-164444.webm](https://user-images.githubusercontent.com/1385470/178818553-bef8620e-579f-4a64-a7bc-255f47932aa2.webm)
@Chapoi any ideas about the period picker position?

FEATURE: Time period filter on leaderboard view

---

.git-blame-ignore-revs
.github/workflows/plugin-linting.yml
Gemfile
Gemfile.lock
app/controllers/admin/admin_gamification_leaderboard_controller.rb
app/controllers/gamification_leaderboard_controller.rb
app/models/gamification_leaderboard.rb
app/models/gamification_score.rb
app/serializers/leaderboard_view_serializer.rb
db/migrate/20220314190045_create_gamification_score_table.rb
db/migrate/20220331203401_add_groups_to_leaderboards.rb
db/migrate/20220623182333_add_excluded_groups_to_leaderboards.rb
lib/directory_integration.rb
lib/scorables/day_visited.rb
lib/scorables/flag_created.rb
lib/scorables/like_given.rb
lib/scorables/like_received.rb
lib/scorables/post_created.rb
lib/scorables/post_read.rb
lib/scorables/scorable.rb
lib/scorables/solutions.rb
lib/scorables/time_read.rb
lib/scorables/topic_created.rb
lib/scorables/user_invited.rb
plugin.rb
spec/jobs/update_scores_for_ten_days_spec.rb
spec/jobs/update_scores_for_today_spec.rb
spec/lib/scorables/shared_scorables_spec.rb
spec/plugin_spec.rb
spec/requests/gamification_leaderboard_controller_spec.rb

- DEV: Enable ruby Syntax Tree format
- DEV: Apply syntax_tree formatting
- DEV: Ignore stree commit from git blame & update ci

syntax tree

---

assets/javascripts/discourse/templates/components/minimal-gamification-leaderboard-row.hbs
assets/javascripts/discourse/templates/components/minimal-gamification-leaderboard.hbs
assets/stylesheets/common/leaderboard-minimal.scss
plugin.rb

Added styling + smaller avatars

UX: leaderboard minimal styling

---

assets/javascripts/discourse/templates/components/minimal-gamification-leaderboard.hbs

Add link to minimal leaderboard

---

assets/javascripts/discourse/components/minimal-gamification-leaderboard.js
assets/javascripts/discourse/templates/components/minimal-gamification-leaderboard-row.hbs
assets/stylesheets/common/leaderboard-minimal.scss

Simply added a crown to the #1 go-getter

UX: add crown

---

.github/workflows/plugin-linting.yml
.github/workflows/plugin-tests.yml
.rubocop.yml
.streerc
Gemfile
Gemfile.lock
app/controllers/admin/admin_gamification_leaderboard_controller.rb
app/models/gamification_leaderboard.rb
spec/requests/gamification_leaderboard_controller_spec.rb

Adds syntax_tree configuration and formats code

DEV: Introduce syntax_tree for ruby formatting

---

assets/javascripts/discourse/components/gamification-leaderboard.js

See
https://meta.discourse.org/t/discourse-gamification/225916/224?u=falco
for context

FIX: Update personal score when changing leaderboard period

---

assets/javascripts/discourse/templates/admin-plugins-gamification.hbs
package.json
yarn.lock

DEV: Use angle bracket syntax

---

lib/discourse_gamification/scorables/solutions.rb

https://meta.discourse.org/t/wishlist-leaderboard-cheers-for-marking-another-users-post-as-solution/271388?u=falco

FEATURE: Don't award points for self-solutions in solved

---

assets/javascripts/discourse/components/modal/recalculate-scores-form.hbs
assets/stylesheets/common/leaderboard.scss

Some styling tweaks to https://github.com/discourse/discourse-gamification/pull/103

UX: Styling tweaks to the recalculate scores modal

---

lib/discourse_gamification/leaderboard_cached_view.rb

Why this change?
Previously, we were querying against the materialized view even when it
does not exists and rescues the `ActiveRecord::StatementInvalid` error.
However, `ActiveRecord` relies on that error being raised to decide if a
transaction should be rolled backed. Since we swallow the error, the
transaction ends up not being rolled back and left in an aborted state
which is not ideal.
What does this change do?
We check for the existence of the materialized view before querying
against it to prevent unnecessary errors.

DEV: Check if materialized view exists before querying against it

---

admin/assets/javascripts/discourse/templates/admin-plugins/show/discourse-gamification-leaderboards/show.hbs

This core PR will change the component API a bit,
so it's easier to remove these for now and add them
back after:
https://github.com/discourse/discourse/pull/27365

DEV: Remove breadcrumbs for now

---

admin/assets/javascripts/discourse/templates/admin-plugins/show/discourse-gamification-leaderboards/show.hbs

Followup to https://github.com/discourse/discourse-gamification/pull/140
adding these back in with the new core component.

FEATURE: Add breadcrumbs to admin config

---

test/javascripts/acceptance/gamification-score-test.js

https://github.com/discourse/discourse/pull/27964

DEV: Fix acceptance test when using the new topic map

---

assets/javascripts/discourse/connectors/user-profile-secondary/gamification-score.hbs
test/javascripts/acceptance/gamification-score-test.js

See https://github.com/discourse/discourse/pull/28398

DEV: Update user-profile-secondary outlet usage

---

lib/discourse_gamification/leaderboard_cached_view.rb

Perform materialized leaderboard creation, refresh, purge and deletion in DB transactions

DEV: Ensure multi-step leaderboard cache operations are atomic
