app/controllers/admin/admin_gamification_leaderboard_controller.rb, assets/javascripts/discourse/controllers/admin-plugins-gamification.js, lib/scorables/post_read.rb, lib/scorables/time_read.rb, spec/lib/scorables/shared_scorables_spec.rb
Fix 
- There was no way to set `Included Group(s)` or `Visible to Group(s)` to empty once they had been set to a group
- update posts_read weight
- update math where we do devision to make sure that we are summing correctly
=> allow leaderboard groups to be empty

assets/stylesheets/common/leaderboard.scss, assets/stylesheets/mobile/leaderboard.scss
Changed the CSS for the ranking so it shows the full number, as intended. There were however alignment issues because
"1111" takes less space than
"8888" making the avatars mis align. The only way I think I can counter this without setting a width (which would lead back to the previous issue) is using a monospace font for these numbers. It's not optimal that the rank is using a different font, but I think that's the best solution in this case and preferable to a constant misalignment.
=> UX bug fix: rank numbers being hidden

app/controllers/gamification_leaderboard_controller.rb, app/models/gamification_leaderboard.rb, app/serializers/leaderboard_view_serializer.rb, assets/javascripts/discourse/components/gamification-leaderboard.js, assets/javascripts/discourse/templates/components/gamification-leaderboard.hbs
If your user was not loaded in the current list of users, then the `you` tab would not be displayed.
I updated the `scores_for` method to take an additional param of `for_user_id: false` so we can access the score for the current_user and position server side, and not fetch it from the user list client side.
=> Always display personal score

app/controllers/gamification_leaderboard_controller.rb, assets/javascripts/discourse/controllers/admin-plugins-gamification.js, assets/javascripts/discourse/templates/admin-plugins-gamification.hbs, lib/guardian.rb, plugin.rb
Selecting `everyone` was not intended and resulted in broken behavior.
Since all the leaderboard settings are to restrict a leaderboard,
leaving any of the setting empty has the same behavior of manually
selecting everyone.
Also moves leaderboard visibility to a guardian method.
=> UX: Disallow selecting everyone group in leaderboard settings

app/controllers/gamification_leaderboard_controller.rb, app/models/gamification_leaderboard.rb, app/serializers/leaderboard_view_serializer.rb, assets/javascripts/discourse/components/minimal-gamification-leaderboard.js, assets/javascripts/discourse/templates/components/minimal-gamification-leaderboard-row.hbs, assets/javascripts/discourse/templates/components/minimal-gamification-leaderboard.hbs
This leaderboard is minimal in that it:
- only displays top 10 users
- does not have a "podium", but only displays a standard list
=> Add minimal leaderboard for extensions

app/controllers/gamification_leaderboard_controller.rb, app/serializers/leaderboard_view_serializer.rb, spec/requests/gamification_leaderboard_controller_spec.rb
user_limit was being converted to_i which meant that it ended up as 0 if that parameter was nil. This commit fixes the issue and thus the failing specs.
Follow up to ab90d4ce415f8ea08e9bc1cca84a26474b67a3af
=> DEV: Fix spec and user_limit nil issues

assets/javascripts/discourse/components/minimal-gamification-leaderboard.js
This lets admins pick a specific leaderboard when invoking this component, for example, when used in the right sidebar blocks theme component.
=> UX: Allow picking any leaderboard in minimal component

assets/javascripts/discourse/controllers/admin-plugins-gamification.js, assets/javascripts/discourse/templates/admin-plugins-gamification.hbs
This commit shows the default leaderboard period on the Leaderboards list page instead of showing empty column.
Before:
After:
=> UX: show default leaderboard period

assets/javascripts/discourse/components/gamification-leaderboard.js
Reported in
https://meta.discourse.org/t/gamification-leaderboard-pagination-doesnt-respect-the-selected-date-period/241261?u=falco
=> FIX: Infinite scrolling of leaderboard must respect period

assets/javascripts/discourse/templates/components/gamification-leaderboard.hbs, config/locales/client.en.yml
- Hides settings link in leaderboard page for non-staff
- Allows i18n of the "Rank" word in leaderboard page
Reported in
https://meta.discourse.org/t/settings-link-appear-to-everyone/250029?u=falco
https://meta.discourse.org/t/the-rank-word-not-translatable/250042?u=falco
=> UX: Small UX polish to the leaderboard page

jobs/scheduled/update_scores_for_ten_days.rb
Using `10.days.ago` returns not only a date but also a time:
```
> 10.days.ago
=> Tue, 27 Dec 2022 14:49:21.870964677 UTC +00:00
```
That means that the score of users on the 10th day would not include
scorables that happened between the day start and the time when the job
was ran, making users lose their score over time. Since we upsert the
score, user score would go down.
Simple fix here is adding `.midnight` to get the full day.
=> FIX: 10 days score calculation was missing partial data of the 10th day

app/controllers/discourse_gamification/admin_gamification_score_event_controller.rb, app/models/discourse_gamification/gamification_leaderboard.rb, app/models/discourse_gamification/gamification_score.rb, app/models/discourse_gamification/gamification_score_event.rb, app/serializers/admin_gamification_score_event_index_serializer.rb, app/serializers/admin_gamification_score_event_serializer.rb, config/routes.rb, db/migrate/20230420185415_create_gamification_score_events.rb, spec/requests/admin_gamification_score_event_controller_spec.rb
Adds a new API to list/create/update custom score events.
Examples:
```bash
curl http://example.com/admin/plugins/gamification/score_events -H "Api-Key: putapikeyhere" -H "Api-Username: system" 
```
```bash
jo -p user_id="13" date="2023-04-14" points="15" description="testing stuff" | curl --json @- -XPOST http://example.com/admin/plugins/gamification/score_events -H "Api-Key: putapikeyhere" -H "Api-Username: system" 
```
```bash
jo -p id="4" points="13" | curl --json @- -XPUT http://example.com/admin/plugins/gamification/score_events -H "Api-Key: putapikeyhere" -H "Api-Username: system" 
```
=> FEATURE: API for custom score events

lib/discourse_gamification/scorables/like_given.rb, spec/lib/scorables/shared_scorables_spec.rb
LikesGiven was awarding likes to the post owner instead of the user who gave the like, making it act like the LikesReceived by mistake.
Test is also fixed as it didn't catch this mistake.
=> FIX: LikensGiven was awarding to wrong user

assets/javascripts/discourse/templates/modal/leaderboard-info.hbs
This allows for additional customization in the "How does the leaderbaord work?" modal.
The modal in question:
&nbsp;
=> DEV: render HTML for leaderboard modal text

app/controllers/discourse_gamification/gamification_leaderboard_controller.rb, app/models/discourse_gamification/gamification_leaderboard.rb, spec/requests/gamification_leaderboard_controller_spec.rb
This commit adds caching for the leaderboard page to improve
performance.
=> DEV: Add caching to the leaderboard page

spec/requests/gamification_leaderboard_controller_spec.rb
Changing the freeze_time delay to be 1 day to hopefully avoid any cache
expiring issues in the test env.
Follow up to: 5c0bfb0a2c88080b630a7f521b8449b5f42a050f
=> DEV: Update failing test

plugin.rb
Enqueuing a job fails if there is not DB yet during `db:migrate`
=> FIX: `db:migrate` rake could fail in dev environment

app/models/discourse_gamification/gamification_leaderboard.rb, lib/discourse_gamification/directory_integration.rb, lib/discourse_gamification/user_extension.rb, spec/lib/directory_integration_spec.rb, spec/lib/scorables/shared_scorables_spec.rb, spec/models/gamification_score_spec.rb, spec/models/user_spec.rb
The standalone user gamification score is presently calculated as the sum of all
available scores earned by a user. This get's displayed on the user card and the
user directory listing. However, there are instances where we want scores(legacy/migrated) retained without them contribute to a user's score.
This change scopes the standalone user gamification score computation to the default leaderboard's from/to date values if available.
=> FEATURE: Scope user score/cheers to default leaderboard date range

config/locales/client.en.yml, config/settings.yml
This is so the plugins settings are better categorized in the site settings UI.
=> DEV: Change settings root from plugins: to discourse_gamification

lib/discourse_gamification/leaderboard_cached_view.rb
Backup/Restore runs lead to most of the `public` schema being copied over to the backup` schema. This leads to `pg_class` returning more than row for materialized view lookups.
This change limits the lookups to the `public` schema.
=> FIX: Scope leaderboard materialized view lookups to public schema

app/serializers/admin_gamification_index_serializer.rb, assets/javascripts/discourse/components/modal/recalculate-scores-form.js, assets/javascripts/discourse/controllers/admin-plugins-gamification.js, assets/javascripts/discourse/routes/admin-plugins-gamification.js, plugin.rb
This commit does some preparation for the core
commit https://github.com/discourse/discourse/pull/26024 to
land, to make the routes for gamification a little more consistent
and also to add the leaderboard/group data to the PluginSerializer,
since in core we will have an /admin/plugins/:id route
on server-side
Part of /t/122841 internally
=> DEV: Move routes around prep work

assets/javascripts/discourse/components/minimal-gamification-leaderboard.hbs
meta topic: https://meta.discourse.org/t/add-translation-for-rank-in-right-sidebar-block-mini-gamification-board/293837
before:
after:
=> UX: Fixed the missing translation issue of "Rank"

admin/assets/javascripts/discourse/controllers/admin-plugins-show-discourse-gamification-leaderboards-index.js, admin/assets/javascripts/discourse/templates/admin-plugins/show/discourse-gamification-leaderboards/index.hbs
Similar to https://github.com/discourse/discourse/pull/27639. This is strictly visual, the actual stored dates are correct.
=> FIX: Incorrect leaderboard range on some timezones

spec/system/page_objects/modals/recalculate_scores_form.rb
Seeing the following error intermittenly in tests due to attempting to select an item in the dropdown before it is expanded. 
```
Unable to find css "#update-range.is-expanded"
```
=> DEV: Expand dropdown explicitly as tests sometimes do not expand it

admin/assets/javascripts/admin/components/admin-create-leaderboard.gjs, admin/assets/javascripts/admin/components/admin-edit-leaderboard.gjs, admin/assets/javascripts/discourse/templates/admin-plugins/show/discourse-gamification-leaderboards/index.hbs, admin/assets/javascripts/discourse/templates/admin-plugins/show/discourse-gamification-leaderboards/show.hbs, assets/stylesheets/common/leaderboard-admin.scss, config/locales/client.en.yml, spec/system/admin_leaderboards_spec.rb, spec/system/page_objects/pages/admin_leaderboards.rb
Also use new AdminPageSubheader component on the
index page for the title and buttons.
=> UX: Convert admin leaderboard forms to FormKit

admin/assets/javascripts/discourse/templates/admin-plugins/show/discourse-gamification-leaderboards/index.hbs, assets/javascripts/discourse/components/gamification-leaderboard.hbs
This PR updates more deprecated Font Awesome icon names. For more detail, refer to the announcement at https://meta.discourse.org/t/-/325349.
=> DEV: Update more deprecated Font Awesome icon names

admin/assets/javascripts/discourse/templates/admin-plugins/show/discourse-gamification-leaderboards/index.hbs
Previously was AdminPageSubheader until https://github.com/discourse/discourse/pull/30146
=> DEV: Change to use DPageSubheader

lib/discourse_gamification/leaderboard_cached_view.rb, spec/lib/leaderboard_cached_view_spec.rb
This change, ensures period filter works within the bounds of the leaderboard's configured date(s) if present. There is currently a bug in the relative period condition in the materialized view query which causes it to take precedence over the leaderboard's date range. Ideally, scores should always be constrained by the leaderboard's dates first, with the relative period filter applied afterward, if applicable.
This change ensures that the period filter respects the leaderboard's configured date bounds, if present.
For example, given a  **November 2024** leaderboard (i.e. `from_date = 2024-11-01` and `to_date = 2024-11-30`) refreshed and queried on `2025-12-02`:
- `all_time`: No period window, only scores created from `2024-11-01` to `2024-11-30`
- `yearly`:  Period starting from …
=> FIX: Redo period filtering to respect leaderboard date bounds

admin/assets/javascripts/admin/components/admin-edit-leaderboard.gjs, app/controllers/discourse_gamification/admin_gamification_leaderboard_controller.rb, app/models/discourse_gamification/gamification_leaderboard.rb, app/serializers/leaderboard_serializer.rb, assets/javascripts/discourse/components/gamification-leaderboard.hbs, assets/javascripts/discourse/models/gamification-leaderboard.js, config/locales/client.en.yml, db/migrate/20250102185307_add_period_filter_disabled_to_leaderboards.rb
Follow up #178 
For some leaderboards, filtering by time period might be unsuitable. This change introduces the option to disable the period chooser in the UI.
=> FEATURE: Add option to lock leaderboard view to default period

plugin.rb
When loading the gamification plugin, we are also
loading all groups for the site, which can load
an upload based on flair_type for the group.
We need to include the flair_upload record
to avoid N1s
=> FIX: N1 on group flair_url

db/post_migrate/20250210133038_drop_versioned_leaderboard_materialized_views.rb, lib/discourse_gamification/leaderboard_cached_view.rb, spec/jobs/update_scores_for_today_spec.rb, spec/jobs/update_stale_leaderboard_positions_spec.rb, spec/lib/leaderboard_cached_view_spec.rb
Leaderboard materialized view names currently include a version number. This versioning mechanism helps with staleness checks and ensures views are seamlessly updated after changes to the backing query. While effective, it also means the view name changes with each version bump, making it unsuitable for use in badge and Data Explorer queries.
Ideally, given the transient nature of these materialized views, they shouldn’t be used in user queries, but we don’t have much control over that.
This change removes explicit version numbers and instead adds a  SQL`COMMENT` to each view containing a signature of the query at the time it was created. This approach maintains the ability to check for staleness without explicitly versioning materialized views.
=> DEV: Remove explicit leaderboard materialize view versions

spec/lib/leaderboard_cached_view_spec.rb
In SQL land, we filter for the scores using `CURRENT_DATE - INTERVAL '1
month'` but in the test setup we are using `Date.current - 30.days`.
These two calculators are different where the former is looking at the date 1
calendar month ago while the latter is just returning the date 30 days
ago.
=> DEV: Fix failing tests depending on the time of the month

lib/discourse_gamification/leaderboard_cached_view.rb, spec/lib/leaderboard_cached_view_spec.rb
Currently, `mview_exists?` returns true if the materialized view existed anywhere in the database, regardless of the schema. This caused issues after backup restores, where the views may exist in the `backup` schema created during the restore but not in the current public schema.
This change ensures the check is scoped to the current schema.
=> FIX: Scope materialized view existence check to current schema

assets/javascripts/discourse/components/minimal-gamification-leaderboard-row.gjs, assets/javascripts/discourse/components/minimal-gamification-leaderboard.gjs, assets/javascripts/discourse/connectors/user-profile-secondary/gamification-score.gjs, assets/javascripts/discourse/controllers/gamification-leaderboard-by-name.js, assets/javascripts/discourse/controllers/gamification-leaderboard-index.js, test/javascripts/components/gamification-leaderboard-row-test.gjs, test/javascripts/components/gamification-leaderboard-test.gjs, test/javascripts/components/gamification-score-test.gjs, test/javascripts/components/minimal-gamification-leaderboard-row-test.gjs, test/javascripts/components/minimal-gamification-leaderboard-test.gjs
* don't modify state in getters
* prefer a getter over a manually updated tracked property
* convert minimal leaderboard row to glimmer
* use qunit-dom
* use local variables over this.set
* use relative imports in tests
* add tests for minimal leaderboard
* fix a test for minimal leaderboard row
* whitespace
* remove gitkeep files
=> DEV: Clean up the code
